from typing import Protocol

from football_system.domain.market_v2 import MarketArtifact


class MultiMarketRepository(Protocol):
    def save(self, artifact: MarketArtifact) -> MarketArtifact: ...
    def load(
        self, artifact_id: str, schema_version: str | None = None
    ) -> MarketArtifact: ...
    def legacy_threeway(
        self, analysis_run_id: str, match_id: str
    ) -> MarketArtifact: ...
    def admit_cohort(self, source: MarketArtifact) -> MarketArtifact: ...
    def results(self, result_ids: tuple[str, ...]) -> tuple: ...
