"""Local contract tests, never real provider data, authority or production approval.

The writer fixture routes existing test-evidence helpers through the public CLI.
Its capture/review/registration times use the actual clock; provider publication
times stay historical. Review documents are supplied externally by test fixtures,
never generated by the CLI. Selected downstream tests reuse a labelled pilot port
double, not a public approval bypass. All files stay in pytest temporary storage.
"""

import json
import sqlite3
from datetime import datetime, timedelta

import pytest
from pydantic import ValidationError
from sqlalchemy import event, text
from sqlalchemy.engine import Engine
from sqlalchemy.exc import IntegrityError, OperationalError

from football_system.domain.archive import canonical_json
from football_system.domain.common import utc_now
from football_system.domain.production_release import (
    TrainingHistoryManifestV1,
)
from football_system.domain.quant_integrity import QuantIntegrityPlanDefinitionV2
from football_system.domain.training_admission import (
    SourceRightsAdmissionV1,
    TrainingFactAdmissionV1,
)
from football_system.domain.training_correction import (
    CORRECTION_INTENT_V2,
    CorrectionCaptureRefV2,
    TrainingCorrectionAdmissionV2,
    TrainingCorrectionContextV2,
    TrainingCorrectionIntentV2,
    TrainingFactVersionV2,
)
from football_system.domain.versioned_training_history import (
    TrainingHistoryContextPinV2,
)
from football_system.infrastructure.database import quant_integrity_repository as quant
from football_system.infrastructure.database.training_admission_repository import (
    TrainingCaptureReceiptV1,
)
from football_system.interfaces import production_quant_cli as cli
from football_system.interfaces.cli import main
from tests.e2e import test_production_quant_cli as previous
from tests.integration import test_corrected_quant_workflow as workflow
from tests.integration import test_training_admission_persistence as admission_cases
from tests.integration import test_training_corrections as correction_cases

lane = previous.lane
offline = previous.offline


@pytest.fixture
def pilot_lane(lane, monkeypatch, request):
    # Reuse the reviewed domestic-league mapping fixture for the actual pilot.
    yield from previous.pilot_tests.actual_admission.__wrapped__(
        lane.root, monkeypatch, request
    )


def public(lane, command, request, capsys, model=None):
    result, response = previous.invoke(lane, command, request, capsys)
    assert result == 0, response
    return model.model_validate(response["result"]) if model else response


def wire_correction_helpers(lane, capsys, monkeypatch):
    # Only fixture entry points are routed; every CLI call constructs fresh real
    # repositories and performs the complete rights/evidence/transaction checks.
    monkeypatch.setattr(
        lane.repo,
        "capture_local_json",
        lambda **values: public(
            lane, "capture", values, capsys, TrainingCaptureReceiptV1
        ),
    )
    monkeypatch.setattr(
        lane.corrections,
        "capture_reference",
        lambda receipt_id, **values: public(
            lane,
            "correction-reference",
            dict(receipt_id=receipt_id, **values),
            capsys,
            CorrectionCaptureRefV2,
        ),
    )

    def prepare(**values):
        lane.prepare_request = values
        lane.preview = public(lane, "correction-prepare", values, capsys)
        return TrainingCorrectionIntentV2.model_validate(lane.preview["result"])

    monkeypatch.setattr(lane.corrections, "prepare", prepare)


@pytest.fixture
def writer(lane, capsys, monkeypatch):
    lane.clock = utc_now
    lane.repo._clock = utc_now
    monkeypatch.setattr(
        lane.repo,
        "record",
        lambda **values: public(
            lane, "rights-record", values, capsys, SourceRightsAdmissionV1
        ),
    )
    monkeypatch.setattr(
        lane.repo,
        "capture_local_json",
        lambda **values: public(
            lane, "capture", values, capsys, TrainingCaptureReceiptV1
        ),
    )
    admission_cases.prepare(lane, count=2)
    admitted = public(
        lane,
        "admit",
        dict(
            request_key="cli-base-admission",
            source_rights_admission_id=lane.recorded.source_rights_admission_id,
            submissions=lane.submissions,
        ),
        capsys,
    )
    lane.admission = TrainingFactAdmissionV1.model_validate(admitted["result"])
    workflow.enable_corrections(lane, lane.admission)
    assert admitted["reference"] == lane.base_pin.model_dump(mode="json")
    context = context_response(lane, capsys)
    lane.base = next(
        TrainingFactVersionV2.model_validate(v)
        for v in context["context"]["versions"]
        if v["snapshot"]["stream"]["internal_match_id"] == "match-0"
    )
    wire_correction_helpers(lane, capsys, monkeypatch)
    return lane


def context_request(lane, ids=(), cutoff=None):
    return dict(
        base_admissions=(lane.base_pin,),
        correction_ids=ids,
        source_cutoffs={
            "source": cutoff or admission_cases.SOURCE + timedelta(days=30)
        },
    )


def context_response(lane, capsys, ids=(), cutoff=None):
    response = public(
        lane, "correction-context", context_request(lane, ids, cutoff), capsys
    )
    assert response["status"] == "VERIFIED"
    return response["result"]


def reviewed_request(lane, capsys, **changes):
    intent, review = correction_cases.reviewed_intent(lane, **changes)
    assert lane.preview["review_subject"] == {
        "schema_version": CORRECTION_INTENT_V2,
        "payload_hash": intent.intent_hash,
    }
    return cli.CorrectionAdmitRequestV2(
        request_key=f"cli-correction-{lane.next_correction}",
        intent=intent,
        reviewer_evidence=review,
        reviewer_authority=lane.correction_authority,
    )


def test_actual_cli_writer_time_free_review_context_order_and_immutable_root(
    writer, capsys, monkeypatch
):
    lane = writer
    base_wire = canonical_json(lane.base_admission)
    request = reviewed_request(lane, capsys, equal_time=True)
    database = lane.root / "lane.db"
    before = database.read_bytes()
    counts = correction_cases.counts(lane)
    with monkeypatch.context() as scoped:
        scoped.setattr(cli, "upgrade_database", lambda *a: pytest.fail("read migrated"))
        repeated = public(lane, "correction-prepare", lane.prepare_request, capsys)
    assert repeated == lane.preview
    assert repeated["status"] == "PREPARED"
    assert database.read_bytes() == before
    assert correction_cases.counts(lane) == counts
    intent = canonical_json(request.intent)
    assert all(key not in intent for key in ("actual_", "registered_at", "reviewed_at"))
    started = utc_now()
    first = public(lane, "correction-admit", request, capsys)
    value = TrainingCorrectionAdmissionV2.model_validate(first["result"])
    assert started <= value.content_payload.actual_started_at_utc <= utc_now()
    assert first["reference"] == value.reference().model_dump(mode="json")
    inspected = public(
        lane,
        "inspect",
        {"target": {"kind": "correction", "artifact_id": value.artifact_id}},
        capsys,
    )
    assert inspected["result"] == first["result"]
    version = public(
        lane,
        "inspect",
        {"target": {"kind": "correction-version", "artifact_id": value.artifact_id}},
        capsys,
        TrainingFactVersionV2,
    )
    second_request = reviewed_request(
        lane, capsys, previous=version, equal_time=True, raw={"home_goals": 4}
    )
    second = public(
        lane, "correction-admit", second_request, capsys, TrainingCorrectionAdmissionV2
    )
    boundary = request.intent.candidate.result_source_available_at_utc
    before_context = context_response(
        lane,
        capsys,
        (second.artifact_id, value.artifact_id),
        boundary - timedelta(microseconds=1),
    )
    assert all(
        v["snapshot"]["stream"]["internal_match_id"] != "match-0"
        for v in before_context["selected_versions"]
    )
    context = context_response(
        lane, capsys, (second.artifact_id, value.artifact_id), boundary
    )
    versions = context["context"]["versions"]
    assert [
        v["revision_sequence"]
        for v in versions
        if v["snapshot"]["stream"]["internal_match_id"] == "match-0"
    ] == [0, 1, 2]
    assert context["selected_heads"][0]["version"] == second.reference().model_dump(
        mode="json"
    )
    assert context["selected_versions"][0]["normalized_result"]["home_goals"] == 4
    pin = TrainingHistoryContextPinV2.of(
        TrainingCorrectionContextV2.model_validate(context["context"])
    )
    assert context["correction_context"] == pin.model_dump(mode="json")
    assert context["context_root"] == pin.context_root
    assert datetime.fromisoformat(
        context["context_registered_at_utc"]
    ) == datetime.fromisoformat(context["context"]["actual_at_utc"])
    assert context["base_root"] != context["context_root"]
    assert all(
        e["predecessor"]["artifact_id"] != "ROOT"
        for e in context["context"]["corrections"]
    )
    assert canonical_json(lane.repo.load(lane.base_pin.artifact_id)) == base_wire
    assert public(lane, "correction-admit", request, capsys) == first
    assert correction_cases.counts(lane)["match_results"] == 4
    for table in (
        "training_correction_streams",
        "training_correction_admissions",
        "training_fact_bindings",
    ):
        for statement in (
            f"UPDATE {table} SET row_sha256=row_sha256",
            f"DELETE FROM {table}",
        ):
            with pytest.raises(IntegrityError), lane.engine.begin() as connection:
                connection.exec_driver_sql(statement)


def test_inclusive_source_cutoff_keeps_original_until_later_publication(writer, capsys):
    lane = writer
    request = reviewed_request(lane, capsys)
    value = public(
        lane, "correction-admit", request, capsys, TrainingCorrectionAdmissionV2
    )
    boundary = request.intent.candidate.result_source_available_at_utc
    early = context_response(
        lane, capsys, (value.artifact_id,), boundary - timedelta(microseconds=1)
    )
    late = context_response(lane, capsys, (value.artifact_id,), boundary)
    assert next(
        v
        for v in early["selected_versions"]
        if v["snapshot"]["stream"]["internal_match_id"] == "match-0"
    )["reference"] == lane.base.reference.model_dump(mode="json")
    assert next(
        v
        for v in late["selected_versions"]
        if v["snapshot"]["stream"]["internal_match_id"] == "match-0"
    )["reference"] == value.reference().model_dump(mode="json")


@pytest.mark.parametrize("status", ["CANCELLED", "WITHDRAWN", "UNMAPPED_STATUS"])
def test_nontrainable_withdrawal_is_returned_without_a_match_result(
    writer, capsys, status
):
    lane = writer
    request = reviewed_request(
        lane,
        capsys,
        trainable=False,
        raw={"status": status},
        omit_result_fields=(
            "home_goals",
            "away_goals",
            "finalized_at_utc",
            "score_semantics",
        ),
    )
    before = correction_cases.counts(lane)["match_results"]
    value = public(
        lane, "correction-admit", request, capsys, TrainingCorrectionAdmissionV2
    )
    context = context_response(lane, capsys, (value.artifact_id,))
    head = next(
        v
        for v in context["selected_versions"]
        if v["snapshot"]["stream"]["internal_match_id"] == "match-0"
    )
    assert head["snapshot"]["provider_raw_status"] == status
    assert head["normalized_result"] is None
    assert value.content_payload.normalized_result is None
    assert correction_cases.counts(lane)["match_results"] == before
    assert (
        next(f for f in context["selected_heads"] if f["match_id"] == "match-0")[
            "match_result_id"
        ]
        is None
    )


@pytest.mark.parametrize(
    "bad",
    [
        "missing-version",
        "v1-adapter",
        "missing-status",
        "ambiguous-status",
        "untrusted-review",
        "changed-intent",
    ],
)
def test_preflight_correction_never_reads_provider_bytes_or_opens_database(
    writer, capsys, monkeypatch, bad
):
    lane = writer
    request = reviewed_request(lane, capsys).model_dump(mode="json")
    if bad == "missing-version":
        request["intent"].pop("schema_version")
    elif bad == "untrusted-review":
        request["reviewer_authority"]["evidence_sha256"] = "0" * 64
    elif bad == "changed-intent":
        request["intent"]["candidate"]["home_goals"] = 9
    else:
        path = (
            lane.root / request["intent"]["evidence"]["adapter"]["evidence_reference"]
        )
        adapter = json.loads(path.read_bytes())
        if bad == "v1-adapter":
            adapter["schema_version"] = "TRAINING_JSON_ADAPTER_V1"
        elif bad == "missing-status":
            adapter["result"].pop("status")
        else:
            adapter["status_rules"].append(adapter["status_rules"][0])
        request["intent"]["evidence"]["adapter"] = admission_cases.write_evidence(
            lane.root, path.name, adapter
        ).model_dump(mode="json")
    original_read = cli.LocalTrainingEvidence.read
    reads = []

    def no_provider(self, reference, expected_sha256=None):
        if reference in {
            "fixture.json",
            "scope.json",
            "result.json",
            "correction-result-1.json",
        }:
            reads.append(reference)
            pytest.fail("preflight read provider bytes")
        return original_read(self, reference, expected_sha256)

    monkeypatch.setattr(cli.LocalTrainingEvidence, "read", no_provider)
    calls = previous.no_database_calls(monkeypatch)
    result, error = previous.invoke(
        lane, "correction-admit", request, capsys, database="absent.db"
    )
    assert result == 2 and error["code"] == "INVALID_LOCAL_INPUT"
    assert error["persistence"] == "NO_DATABASE_OPENED"
    assert not reads and not calls
    assert not (lane.root / "absent.db").exists()


def test_expired_operational_rights_precede_new_provider_reads_but_audit_retry_is_historical(
    writer, capsys, monkeypatch
):
    lane = writer
    request = reviewed_request(lane, capsys)
    response = public(lane, "correction-admit", request, capsys)
    monkeypatch.setattr(
        cli, "utc_now", lambda: lane.rights.expires_at_utc + timedelta(seconds=1)
    )
    original_read = cli.LocalTrainingEvidence.read
    reads = []

    def observe(self, reference, expected_sha256=None):
        if reference == "correction-result-1.json":
            reads.append(reference)
        return original_read(self, reference, expected_sha256)

    monkeypatch.setattr(cli.LocalTrainingEvidence, "read", observe)
    for command, changed in (
        (
            "capture",
            dict(
                request_key="expired",
                source_rights_admission_id=lane.recorded.source_rights_admission_id,
                source_id="source",
                provider_code="PROVIDER",
                evidence_reference="correction-result-1.json",
            ),
        ),
        ("correction-admit", request.model_copy(update={"request_key": "expired-new"})),
        ("correction-prepare", lane.prepare_request),
    ):
        reads.clear()
        result, error = previous.invoke(lane, command, changed, capsys)
        assert result == 1 and error["code"] == "OPERATION_REJECTED"
        assert reads == []
    assert public(lane, "correction-admit", request, capsys) == response
    assert reads
    ref = public(
        lane,
        "correction-reference",
        dict(
            receipt_id=request.intent.evidence.result.capture_receipt_id,
            record_pointer="",
        ),
        capsys,
    )
    assert ref["result"] == request.intent.evidence.result.model_dump(mode="json")
    assert context_response(lane, capsys, (response["result"]["artifact_id"],))[
        "selected_heads"
    ]


@pytest.mark.parametrize("bad", ["missing-raw", "wrong-reviewer", "after-insert"])
def test_correction_admit_failure_is_atomic(writer, capsys, monkeypatch, bad):
    lane = writer
    request = reviewed_request(lane, capsys)
    if bad == "missing-raw":
        (lane.root / "correction-result-1.json").unlink()
    elif bad == "wrong-reviewer":
        doc = json.loads(
            (lane.root / request.reviewer_evidence.evidence_reference).read_bytes()
        )
        doc["authorized_reviewer"] = "not-authorized"
        review = admission_cases.write_evidence(lane.root, "wrong-reviewer.json", doc)
        request = request.model_copy(update={"reviewer_evidence": review})

    def fail_after_insert(
        connection, cursor, statement, parameters, context, executemany
    ):
        if bad == "after-insert" and statement.startswith(
            "INSERT INTO training_correction_admissions"
        ):
            raise OSError(previous.SECRET)

    before = correction_cases.counts(lane)
    event.listen(Engine, "after_cursor_execute", fail_after_insert)
    try:
        result, error = previous.invoke(lane, "correction-admit", request, capsys)
    finally:
        event.remove(Engine, "after_cursor_execute", fail_after_insert)
    assert result == 1 and error["code"] == "OPERATION_REJECTED"
    assert error["persistence"] == "ATOMIC_NO_NEW_ROWS"
    assert "failed atomically" in error["message"]
    assert correction_cases.counts(lane) == before


def test_no_output_overwrite_postcommit_failure_exact_retry_and_same_key_change(
    writer, capsys, monkeypatch
):
    lane = writer
    request = reviewed_request(lane, capsys)
    output = previous.write_request(
        lane.root, b"existing private output", "existing.json"
    )
    before = correction_cases.counts(lane)
    with monkeypatch.context() as scoped:
        calls = previous.no_database_calls(scoped)
        assert (
            previous.invoke(
                lane,
                "correction-admit",
                request,
                capsys,
                extra=("--output", str(output)),
            )[0]
            == 2
        )
        assert calls == []
    assert output.read_bytes() == b"existing private output"
    assert correction_cases.counts(lane) == before

    def fail_output(*args):
        raise OSError(previous.SECRET)

    with monkeypatch.context() as scoped:
        scoped.setattr(cli, "write_local_json", fail_output)
        result, error = previous.invoke(
            lane,
            "correction-admit",
            request,
            capsys,
            extra=("--output", str(lane.root / "failed.json")),
        )
    assert result == 1 and error["code"] == "OUTPUT_NOT_WRITTEN"
    assert error["persistence"] == "MAY_HAVE_PERSISTED"
    assert "exact same request key" in error["message"]
    recorded = correction_cases.counts(lane)
    assert recorded["training_correction_admissions"] == 1
    first = public(lane, "correction-admit", request, capsys)
    assert public(lane, "correction-admit", request, capsys) == first
    changed_review = admission_cases.write_evidence(
        lane.root,
        "changed-review.json",
        admission_cases.review_document(
            schema=CORRECTION_INTENT_V2, digest=request.intent.intent_hash, at=utc_now()
        ),
    )
    result, error = previous.invoke(
        lane,
        "correction-admit",
        request.model_copy(update={"reviewer_evidence": changed_review}),
        capsys,
    )
    assert result == 1 and error["persistence"] == "ATOMIC_NO_NEW_ROWS"
    assert correction_cases.counts(lane) == recorded


@pytest.mark.parametrize(
    "command",
    ["correction-reference", "correction-prepare", "correction-context", "inspect"],
)
def test_correction_reads_are_mode_ro_no_migration_and_output_failure_cannot_claim_persistence(
    writer, capsys, monkeypatch, command
):
    lane = writer
    request = reviewed_request(lane, capsys)
    requests = {
        "correction-reference": dict(
            receipt_id=request.intent.evidence.result.capture_receipt_id,
            record_pointer="",
        ),
        "correction-prepare": lane.prepare_request,
        "correction-context": context_request(lane),
        "inspect": {
            "target": {
                "kind": "correction-version",
                "artifact_id": lane.base.version_id,
            }
        },
    }
    original = cli._execute

    def readonly(command, request, admissions, pilots, production, **kwargs):
        with admissions._sessions.kw["bind"].connect() as connection:
            with pytest.raises(OperationalError, match="readonly"):
                connection.execute(text("CREATE TABLE forbidden_write (id INTEGER)"))
        return original(command, request, admissions, pilots, production, **kwargs)

    monkeypatch.setattr(cli, "_execute", readonly)
    monkeypatch.setattr(
        cli, "upgrade_database", lambda *a: pytest.fail("read migrated")
    )
    result, error = previous.invoke(
        lane, command, requests[command], capsys, database="absent.db"
    )
    assert result == 1 and error["code"] == "DATABASE_NOT_READY"
    assert not (lane.root / "absent.db").exists()
    old = lane.root / "old.db"
    with sqlite3.connect(old) as connection:
        connection.execute("CREATE TABLE alembic_version (version_num TEXT NOT NULL)")
        connection.execute("INSERT INTO alembic_version VALUES ('c2ebf618d354')")
    old_bytes = old.read_bytes()
    result, error = previous.invoke(
        lane, command, requests[command], capsys, database="old.db"
    )
    assert result == 1 and error["code"] == "OPERATION_REJECTED"
    assert error["persistence"] == "NO_NEW_ROWS"
    assert old.read_bytes() == old_bytes
    before = (lane.root / "lane.db").read_bytes()
    public(lane, command, requests[command], capsys)

    def fail_output(*args):
        raise OSError(previous.SECRET)

    monkeypatch.setattr(cli, "write_local_json", fail_output)
    result, error = previous.invoke(
        lane,
        command,
        requests[command],
        capsys,
        extra=("--output", str(lane.root / "failed-read.json")),
    )
    assert result == 1 and error["code"] == "OUTPUT_NOT_WRITTEN"
    assert error["persistence"] == "NO_NEW_ROWS"
    assert "already be persisted" not in error["message"]
    assert (lane.root / "lane.db").read_bytes() == before


@pytest.mark.parametrize(
    "changes,extra",
    [
        ({"actual_at": "2025-01-01T00:00:00Z"}, ()),
        ({"actual_at_utc": "2025-01-01T00:00:00Z"}, ()),
        ({}, ("--as-of", previous.SECRET)),
        ({"source_cutoffs": {}}, ()),
        ({"correction_ids": ["duplicate", "duplicate"]}, ()),
    ],
)
def test_context_rejects_caller_actual_clock_and_ambiguous_pins_before_database(
    writer, capsys, monkeypatch, changes, extra
):
    calls = previous.no_database_calls(monkeypatch)
    result, error = previous.invoke(
        writer,
        "correction-context",
        {**context_request(writer), **changes},
        capsys,
        extra=extra,
    )
    assert result == 2 and error["code"] == "INVALID_LOCAL_INPUT"
    assert calls == []


def test_v2_plan_cli_real_pilot_and_explicit_request_schema(
    pilot_lane, capsys, monkeypatch
):
    lane = pilot_lane
    lane.clock = utc_now
    lane.repo._clock = utc_now
    workflow.enable_corrections(lane, lane.admission)
    wire_correction_helpers(lane, capsys, monkeypatch)
    monkeypatch.setattr(
        quant, "_code_revision", lambda: "package:cli-correction-contract-only"
    )
    request = reviewed_request(lane, capsys, raw={"home_goals": 0})
    correction = public(
        lane, "correction-admit", request, capsys, TrainingCorrectionAdmissionV2
    )
    output = context_response(lane, capsys, (correction.artifact_id,))
    context = lane.corrections.load_context(
        base_admissions=(lane.base_pin,),
        correction_ids=(correction.artifact_id,),
        actual_at=datetime.fromisoformat(output["context_registered_at_utc"]),
    )
    definition = workflow.pilot_definition(lane, context)
    assert (
        definition.correction_context.model_dump(mode="json")
        == output["correction_context"]
    )
    parsed = cli.PilotPlanRequest.model_validate({"definition": definition})
    assert isinstance(parsed.root, cli.PilotPlanRequestV2)
    assert isinstance(parsed.root.definition, QuantIntegrityPlanDefinitionV2)
    assert main(["production-quant", "pilot-plan", "--print-schema"]) == 0
    schema = json.loads(capsys.readouterr().out)
    assert (
        "correction_context"
        in schema["$defs"]["QuantIntegrityPlanDefinitionV2"]["required"]
    )
    assert "QuantIntegrityTargetV2" in schema["$defs"]
    assert (
        main(
            [
                "production-quant",
                "--print-schema",
                "--type",
                "QuantIntegrityPlanDefinitionV2",
            ]
        )
        == 0
    )
    assert (
        json.loads(capsys.readouterr().out)
        == QuantIntegrityPlanDefinitionV2.model_json_schema()
    )
    with pytest.raises(ValidationError):
        parsed.root = cli.PilotPlanRequestV1.model_construct()
    for bad in (
        "missing-version",
        "missing-context",
        "missing-context-version",
        "missing-target-version",
        "missing-fact-version",
        "legacy-versioned-target",
    ):
        raw = definition.model_dump(mode="json")
        if bad in {"missing-version", "legacy-versioned-target"}:
            raw.pop("schema_version")
        if bad in {"missing-context", "legacy-versioned-target"}:
            raw.pop("correction_context")
            raw.pop("context_registered_at_utc")
        if bad == "missing-target-version":
            raw["slices"][0]["content_payload"]["targets"][0].pop("schema_version")
        if bad == "missing-context-version":
            raw["correction_context"].pop("schema_version")
        if bad == "missing-fact-version":
            raw["slices"][0]["content_payload"]["targets"][0]["fact"].pop(
                "schema_version"
            )
        with monkeypatch.context() as scoped:
            calls = previous.no_database_calls(scoped)
            assert (
                previous.invoke(lane, "pilot-plan", {"definition": raw}, capsys)[0] == 2
            )
            assert calls == []
    plan = public(lane, "pilot-plan", {"definition": definition}, capsys)
    assert plan["result"]["content_payload"]["definition"] == definition.model_dump(
        mode="json"
    )
    assert (
        plan["result"]["content_payload"]["input_roots"]["context_root"]
        == output["context_root"]
    )
    report = public(lane, "pilot-run", {"plan_ref": plan["reference"]}, capsys)
    terminal = public(lane, "pilot-attest", {"plan_ref": plan["reference"]}, capsys)
    assert (
        report["result"]["content_payload"]["provenance"]["production_authorized"]
        is False
    )
    manifest = dict(
        schema_version="PRODUCTION_QUANT_MANIFEST_REQUEST_V2",
        request_key="cli-corrected-manifest",
        admission_ids=(lane.base_pin.artifact_id,),
        training_window=definition.training_window,
        integrity_pilot_scope_id=plan["integrity_pilot_scope_id"],
        attestation_id=terminal["result"]["artifact_id"],
        correction_context=output["correction_context"],
        context_registered_at_utc=output["context_registered_at_utc"],
        selection_cutoff_at_utc=definition.terminal_projection.training_cutoff_at_utc,
    )
    assert isinstance(
        cli.ManifestRequest.model_validate(manifest).root, cli.ManifestRequestV2
    )
    for field in (
        "schema_version",
        "correction_context",
        "context_registered_at_utc",
        "selection_cutoff_at_utc",
    ):
        with monkeypatch.context() as scoped:
            calls = previous.no_database_calls(scoped)
            assert (
                previous.invoke(
                    lane,
                    "manifest",
                    {k: v for k, v in manifest.items() if k != field},
                    capsys,
                )[0]
                == 2
            )
            assert calls == []
    # A real synthetic pilot cannot be relabelled as production technical evidence.
    result, error = previous.invoke(lane, "manifest", manifest, capsys)
    assert result == 1 and error["code"] == "OPERATION_REJECTED"


def test_cli_corrected_manifest_v2_approval_predecessor_release_live_and_downstream(
    lane, capsys, monkeypatch
):
    from football_system.domain.production_release import (
        ProductionQuantModelReleaseV1,
        ProductionTargetAcceptancePlanV1,
        TrainingHistoryApprovalPayloadV2,
        TrainingHistoryApprovalV2,
    )
    from football_system.infrastructure.files.production_audit_bundle import (
        read_production_audit_bundle,
    )
    from tests.e2e import test_production_live_cli as live_tests
    from tests.e2e import test_training_approval_v2_cli as approval_cli
    from tests.integration import test_production_audit as audit_cases
    from tests.integration import test_production_inference as inference_cases
    from tests.integration import test_production_quant_persistence as legacy
    from tests.integration import test_training_approval_v2 as approvals

    recorded = []
    releases = []

    def approve(context, manifest, key, predecessor=None):
        payload = public(
            lane,
            "approval-prepare",
            approvals.prepare_values(context, manifest, predecessor=predecessor),
            capsys,
            TrainingHistoryApprovalPayloadV2,
        )
        # External test reviewer, not CLI-created authority/attestation.
        request = cli.ApprovalRecordRequestV2(
            request_key=key,
            approval_payload=payload,
            reviewer_attestation=approvals.review_v2(context, payload),
        )
        value = public(
            lane, "approval-record", request, capsys, TrainingHistoryApprovalV2
        )
        assert (
            public(lane, "approval-record", request, capsys, TrainingHistoryApprovalV2)
            == value
        )
        recorded.append(value)
        release = public(
            lane,
            "release-build",
            dict(
                request_key=key + "-release",
                approval_id=value.artifact_id,
                training_cutoff_at_utc=lane.clock(),
                state_retention_horizon=legacy.horizon(),
                audit_retention_horizon=legacy.horizon(),
            ),
            capsys,
            ProductionQuantModelReleaseV1,
        )
        releases.append(release)
        return release

    def build(context):
        approval_cli.wire_cli(context, monkeypatch)
        legacy_request = dict(
            request_key="cli-original-manifest",
            admission_ids=(context.admission.training_fact_admission_id,),
            training_window=context.window,
            integrity_pilot_scope_id="test-scope",
            attestation_id="test-attestation",
        )
        parsed = cli.ManifestRequest.model_validate(legacy_request).root
        assert type(parsed) is cli.ManifestRequestV1
        assert "schema_version" not in parsed.model_dump()
        manifest = public(
            lane, "manifest", legacy_request, capsys, TrainingHistoryManifestV1
        )
        approve(context, manifest, "cli-original-approval")
        workflow.enable_corrections(lane, context.admission)
        wire_correction_helpers(lane, capsys, monkeypatch)
        correction = public(
            lane,
            "correction-admit",
            reviewed_request(lane, capsys, raw={"home_goals": 0}),
            capsys,
            TrainingCorrectionAdmissionV2,
        )
        output = context_response(lane, capsys, (correction.artifact_id,))
        with lane.sessions.begin() as session:
            session.execute(text("BEGIN"))
            graph = context.repo._prepare_history(
                session,
                admissions=(context.admission,),
                correction_context=TrainingHistoryContextPinV2.model_validate(
                    output["correction_context"]
                ),
                context_registered_at_utc=datetime.fromisoformat(
                    output["context_registered_at_utc"]
                ),
                training_window=context.window,
                integrity_pilot_scope_id="test-scope",
                selection_cutoff_at_utc=admission_cases.SOURCE + timedelta(days=30),
            )
        # Only the established labelled technical port is substituted. Both V2
        # approvals, including the predecessor, use the official public recorder.
        registry = workflow.SyntheticBridgeRegistry(context)
        evidence = context.bridge.evidence.model_copy(
            update=dict(
                plan=legacy.ref("cli-corrected-plan"),
                attestation=legacy.ref("cli-corrected-attestation"),
                source_root=graph.source_root,
                season_root=graph.season_root,
                approved_facts_hash=graph.approved_facts_hash,
                training_data_hash=graph.training_data_hash,
                plan_sealed_at_utc=lane.clock(),
                actual_started_at_utc=lane.clock(),
                actual_completed_at_utc=lane.clock(),
                attestation_persisted_at_utc=lane.clock(),
            )
        )
        registry.values[evidence.attestation.artifact_id] = graph, evidence
        context.bridge = registry
        context.repo.pilot_repository = registry
        request = cli.ManifestRequestV2(
            **{
                **legacy_request,
                "request_key": "cli-corrected-manifest",
                "attestation_id": evidence.attestation.artifact_id,
            },
            schema_version="PRODUCTION_QUANT_MANIFEST_REQUEST_V2",
            correction_context=output["correction_context"],
            context_registered_at_utc=output["context_registered_at_utc"],
            selection_cutoff_at_utc=admission_cases.SOURCE + timedelta(days=30),
            exclude_match_ids=(),
        )
        manifest = public(lane, "manifest", request, capsys, TrainingHistoryManifestV1)
        assert (
            manifest.content_payload.history.context_pin.context_root
            == output["context_root"]
        )
        assert (
            public(lane, "manifest", request, capsys, TrainingHistoryManifestV1)
            == manifest
        )
        release = approve(context, manifest, "cli-corrected-approval", recorded[0])
        assert context.repo.load_release(releases[0].artifact_id) == releases[0]
        with pytest.raises(ValueError, match="correction"):
            context.repo.authorization(releases[0].artifact_id, lane.clock())

        def target_plan(*args):
            return public(
                lane,
                "target-plan",
                dict(zip(cli.TargetPlanRequestV1.model_fields, args, strict=True)),
                capsys,
                ProductionTargetAcceptancePlanV1,
            )

        monkeypatch.setattr(context.repo, "seal_target_plan", target_plan)
        return release

    with monkeypatch.context() as scoped:
        scoped.setattr(legacy, "build", build)
        context = inference_cases.inference.__wrapped__(lane, monkeypatch)
    assert recorded[1].subject.supersedes_approval == recorded[0].reference()
    assert all(a.schema_version == "TRAINING_HISTORY_APPROVAL_V2" for a in recorded)
    context = live_tests.live_cli.__wrapped__(context, monkeypatch)
    assert main(live_tests.arguments(context)) == 0
    captured = capsys.readouterr()
    assert "APPROVED_TRAINING_HISTORY" in captured.out
    assert previous.SECRET not in captured.out + captured.err
    bundle_path = lane.root / "corrected-audit-bundle"
    public(
        lane,
        "bundle-export",
        cli.BundleExportRequestV1(
            analysis_run_id="production-cli-analysis", bundle_directory=bundle_path
        ),
        capsys,
    )
    bundle = read_production_audit_bundle(bundle_path)
    assert bundle.packet.schema_version == "ANALYSIS_PACKET_V3"
    assert bundle.audit.content_payload.approval == recorded[1].reference()
    review_path = previous.write_request(
        lane.root, audit_cases.review_bytes(bundle.packet), "corrected-llm-review.json"
    )
    imported = public(
        lane,
        "review-import",
        cli.ReviewImportRequestV1(
            bundle_directory=bundle_path, review_file=review_path
        ),
        capsys,
    )
    config = previous.write_request(
        lane.root, b'[runtime]\nenvironment = "live"\n', "corrected-live.toml"
    )
    fusion = public(
        lane,
        "fusion-create",
        cli.FusionCreateRequestV1(
            review_artifact_id=imported["result"]["review_artifact_id"],
            config_file=config,
        ),
        capsys,
    )
    revision = public(
        lane,
        "portfolio-revise",
        cli.PortfolioReviseRequestV1(
            fusion_run_id=fusion["result"]["fusion_run_id"], config_file=config
        ),
        capsys,
    )
    assert revision["result"]["portfolio_revision_id"]
    assert legacy.counts(context.production)["training_history_approval_events"] == 2
    assert inference_cases.model_counts(context)["analysis_runs"] == 1
