"""create mvp schema

Revision ID: 1bec5f575834
Revises:
Create Date: 2026-08-31 11:36:04.109407
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '1bec5f575834'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('analysis_run_id', sa.String(length=160), nullable=False),
    sa.Column('run_kind', sa.String(length=80), nullable=False),
    sa.Column('as_of_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('started_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pipeline_version', sa.String(length=80), nullable=False),
    sa.Column('code_revision', sa.String(length=80), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('config_hash', sa.String(length=160), nullable=False),
    sa.Column('input_manifest_version', sa.String(length=80), nullable=False),
    sa.Column('input_manifest_json', sa.Text(), nullable=False),
    sa.Column('input_manifest_hash', sa.String(length=160), nullable=False),
    sa.Column('replay_of_run_id', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['replay_of_run_id'], ['analysis_runs.analysis_run_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('analysis_run_id')
    )
    op.create_table('bookmakers',
    sa.Column('bookmaker_id', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('bookmaker_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('competitions',
    sa.Column('competition_id', sa.String(length=160), nullable=False),
    sa.Column('canonical_key', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('competition_id'),
    sa.UniqueConstraint('canonical_key')
    )
    op.create_table('providers',
    sa.Column('provider_id', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('provider_kind', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('provider_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.String(length=160), nullable=False),
    sa.Column('canonical_key', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('team_type', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('canonical_key')
    )
    op.create_table('matches',
    sa.Column('internal_match_id', sa.String(length=160), nullable=False),
    sa.Column('competition_id', sa.String(length=160), nullable=False),
    sa.Column('home_team_id', sa.String(length=160), nullable=False),
    sa.Column('away_team_id', sa.String(length=160), nullable=False),
    sa.Column('kickoff_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('available_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('home_team_id <> away_team_id', name='ck_matches_distinct_teams'),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.competition_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('internal_match_id')
    )
    op.create_index('ix_matches_competition_kickoff', 'matches', ['competition_id', 'kickoff_at_utc'], unique=False)
    op.create_table('manual_quant_inputs',
    sa.Column('input_id', sa.String(length=160), nullable=False),
    sa.Column('internal_match_id', sa.String(length=160), nullable=False),
    sa.Column('market_key', sa.String(length=120), nullable=False),
    sa.Column('market_type', sa.String(length=64), nullable=False),
    sa.Column('handicap_value', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('available_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_hash', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['internal_match_id'], ['matches.internal_match_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('input_id'),
    sa.UniqueConstraint('internal_match_id', 'market_key', 'available_at_utc', 'payload_hash', name='uq_manual_quant_version')
    )
    op.create_table('manual_quant_input_outcomes',
    sa.Column('input_id', sa.String(length=160), nullable=False),
    sa.Column('selection_key', sa.String(length=64), nullable=False),
    sa.Column('probability', sa.Numeric(precision=18, scale=12), nullable=False),
    sa.CheckConstraint("selection_key IN ('HOME_WIN', 'DRAW', 'AWAY_WIN')", name='ck_manual_quant_selection'),
    sa.CheckConstraint('probability >= 0 AND probability <= 1', name='ck_manual_quant_probability'),
    sa.ForeignKeyConstraint(['input_id'], ['manual_quant_inputs.input_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('input_id', 'selection_key')
    )
    op.create_table('portfolios',
    sa.Column('portfolio_id', sa.String(length=160), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=160), nullable=False),
    sa.Column('budget_fen', sa.Integer(), nullable=False),
    sa.Column('total_stake_fen', sa.Integer(), nullable=False),
    sa.Column('unused_budget_fen', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('no_bet_reason', sa.String(length=80), nullable=True),
    sa.Column('strategy_version', sa.String(length=80), nullable=False),
    sa.Column('strategy_config_json', sa.Text(), nullable=False),
    sa.CheckConstraint('budget_fen >= 0', name='ck_portfolio_budget'),
    sa.CheckConstraint('total_stake_fen <= budget_fen', name='ck_portfolio_within_budget'),
    sa.CheckConstraint('total_stake_fen >= 0', name='ck_portfolio_stake'),
    sa.CheckConstraint('unused_budget_fen >= 0', name='ck_portfolio_unused'),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.analysis_run_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('portfolio_id'),
    sa.UniqueConstraint('analysis_run_id', 'budget_fen', name='uq_portfolio_run_budget')
    )
    op.create_table('ticket_candidates',
    sa.Column('ticket_candidate_id', sa.String(length=160), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=160), nullable=False),
    sa.Column('pass_type', sa.String(length=64), nullable=False),
    sa.Column('atomic_bet_count', sa.Integer(), nullable=False),
    sa.Column('base_stake_fen', sa.Integer(), nullable=False),
    sa.Column('joint_probability', sa.Numeric(precision=18, scale=12), nullable=False),
    sa.Column('gross_payout_fen', sa.Integer(), nullable=False),
    sa.Column('expected_gross_payout_fen', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('expected_profit_fen', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('expected_roi', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('payout_policy_version', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.analysis_run_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ticket_candidate_id')
    )
    op.create_table('market_odds_snapshots',
    sa.Column('snapshot_id', sa.String(length=160), nullable=False),
    sa.Column('internal_match_id', sa.String(length=160), nullable=False),
    sa.Column('provider_id', sa.String(length=160), nullable=False),
    sa.Column('bookmaker_id', sa.String(length=160), nullable=False),
    sa.Column('market_key', sa.String(length=120), nullable=False),
    sa.Column('market_type', sa.String(length=64), nullable=False),
    sa.Column('handicap_value', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('captured_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_snapshot_key', sa.String(length=160), nullable=False),
    sa.Column('payload_hash', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.bookmaker_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['internal_match_id'], ['matches.internal_match_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('provider_id', 'source_snapshot_key', name='uq_market_source_key')
    )
    op.create_index('ix_market_odds_match_bookmaker_time', 'market_odds_snapshots', ['internal_match_id', 'bookmaker_id', 'available_at_utc', 'captured_at_utc'], unique=False)
    op.create_table('market_probabilities',
    sa.Column('market_probability_id', sa.String(length=160), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=160), nullable=False),
    sa.Column('internal_match_id', sa.String(length=160), nullable=False),
    sa.Column('market_key', sa.String(length=120), nullable=False),
    sa.Column('market_type', sa.String(length=64), nullable=False),
    sa.Column('handicap_value', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('devig_method', sa.String(length=80), nullable=False),
    sa.Column('devig_version', sa.String(length=40), nullable=False),
    sa.Column('overround', sa.Numeric(precision=18, scale=12), nullable=False),
    sa.Column('generated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.analysis_run_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['internal_match_id'], ['matches.internal_match_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('market_probability_id'),
    sa.UniqueConstraint('analysis_run_id', 'internal_match_id', 'market_key', name='uq_market_probability')
    )
    op.create_table('provider_match_mappings',
    sa.Column('mapping_id', sa.String(length=160), nullable=False),
    sa.Column('provider_id', sa.String(length=160), nullable=False),
    sa.Column('external_namespace', sa.String(length=80), nullable=False),
    sa.Column('external_match_id', sa.String(length=160), nullable=False),
    sa.Column('internal_match_id', sa.String(length=160), nullable=False),
    sa.Column('resolution_method', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=18, scale=12), nullable=False),
    sa.Column('available_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supersedes_mapping_id', sa.String(length=160), nullable=True),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_mapping_confidence'),
    sa.ForeignKeyConstraint(['internal_match_id'], ['matches.internal_match_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_mapping_id'], ['provider_match_mappings.mapping_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('mapping_id'),
    sa.UniqueConstraint('provider_id', 'external_namespace', 'external_match_id', name='uq_provider_external_match')
    )
    op.create_table('quant_predictions',
    sa.Column('quant_prediction_id', sa.String(length=160), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=160), nullable=False),
    sa.Column('internal_match_id', sa.String(length=160), nullable=False),
    sa.Column('market_key', sa.String(length=120), nullable=False),
    sa.Column('market_type', sa.String(length=64), nullable=False),
    sa.Column('handicap_value', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('manual_input_id', sa.String(length=160), nullable=False),
    sa.Column('input_payload_hash', sa.String(length=160), nullable=False),
    sa.Column('method', sa.String(length=80), nullable=False),
    sa.Column('method_version', sa.String(length=80), nullable=False),
    sa.Column('entered_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.analysis_run_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['internal_match_id'], ['matches.internal_match_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manual_input_id'], ['manual_quant_inputs.input_id'], name='fk_quant_predictions_manual_input_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('quant_prediction_id'),
    sa.UniqueConstraint('analysis_run_id', 'internal_match_id', 'market_key', name='uq_quant_prediction')
    )
    op.create_table('sporttery_bonus_snapshots',
    sa.Column('snapshot_id', sa.String(length=160), nullable=False),
    sa.Column('internal_match_id', sa.String(length=160), nullable=False),
    sa.Column('provider_id', sa.String(length=160), nullable=False),
    sa.Column('sporttery_match_no', sa.String(length=80), nullable=False),
    sa.Column('market_key', sa.String(length=120), nullable=False),
    sa.Column('market_type', sa.String(length=64), nullable=False),
    sa.Column('handicap_value', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('sale_status', sa.String(length=64), nullable=False),
    sa.Column('captured_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_snapshot_key', sa.String(length=160), nullable=False),
    sa.Column('payload_hash', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['internal_match_id'], ['matches.internal_match_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('provider_id', 'source_snapshot_key', name='uq_sporttery_source_key')
    )
    op.create_index('ix_sporttery_bonus_match_time', 'sporttery_bonus_snapshots', ['internal_match_id', 'available_at_utc', 'captured_at_utc'], unique=False)
    op.create_table('tickets',
    sa.Column('ticket_id', sa.String(length=160), nullable=False),
    sa.Column('portfolio_id', sa.String(length=160), nullable=False),
    sa.Column('ticket_candidate_id', sa.String(length=160), nullable=False),
    sa.Column('ticket_no', sa.Integer(), nullable=False),
    sa.Column('pass_type', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.Column('atomic_bet_count', sa.Integer(), nullable=False),
    sa.Column('base_stake_fen', sa.Integer(), nullable=False),
    sa.Column('stake_fen', sa.Integer(), nullable=False),
    sa.Column('potential_gross_payout_fen', sa.Integer(), nullable=False),
    sa.Column('expected_gross_payout_fen', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('expected_profit_fen', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('expected_roi', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('probability_any_payout', sa.Numeric(precision=18, scale=12), nullable=False),
    sa.Column('payout_policy_version', sa.String(length=80), nullable=False),
    sa.CheckConstraint('atomic_bet_count >= 1', name='ck_ticket_atomic_count'),
    sa.CheckConstraint('base_stake_fen > 0', name='ck_ticket_base_stake'),
    sa.CheckConstraint('multiplier >= 1', name='ck_ticket_multiplier'),
    sa.CheckConstraint('stake_fen = atomic_bet_count * base_stake_fen * multiplier', name='ck_ticket_derived_stake'),
    sa.CheckConstraint('ticket_no > 0', name='ck_ticket_no'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_candidate_id'], ['ticket_candidates.ticket_candidate_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ticket_id'),
    sa.UniqueConstraint('portfolio_id', 'ticket_no', name='uq_portfolio_ticket_no')
    )
    op.create_table('analysis_run_matches',
    sa.Column('analysis_run_id', sa.String(length=160), nullable=False),
    sa.Column('internal_match_id', sa.String(length=160), nullable=False),
    sa.Column('market_odds_snapshot_id', sa.String(length=160), nullable=False),
    sa.Column('sporttery_bonus_snapshot_id', sa.String(length=160), nullable=False),
    sa.Column('manual_quant_input_id', sa.String(length=160), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=False),
    sa.Column('context_hash', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.analysis_run_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['internal_match_id'], ['matches.internal_match_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['market_odds_snapshot_id'], ['market_odds_snapshots.snapshot_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manual_quant_input_id'], ['manual_quant_inputs.input_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sporttery_bonus_snapshot_id'], ['sporttery_bonus_snapshots.snapshot_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('analysis_run_id', 'internal_match_id')
    )
    op.create_table('final_predictions',
    sa.Column('final_prediction_id', sa.String(length=160), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=160), nullable=False),
    sa.Column('internal_match_id', sa.String(length=160), nullable=False),
    sa.Column('market_key', sa.String(length=120), nullable=False),
    sa.Column('market_type', sa.String(length=64), nullable=False),
    sa.Column('handicap_value', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('market_probability_id', sa.String(length=160), nullable=True),
    sa.Column('quant_prediction_id', sa.String(length=160), nullable=True),
    sa.Column('llm_assessment_id', sa.String(length=160), nullable=True),
    sa.Column('fusion_policy', sa.String(length=64), nullable=False),
    sa.Column('fusion_version', sa.String(length=40), nullable=False),
    sa.Column('fusion_config_json', sa.Text(), nullable=False),
    sa.Column('fallback_code', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=18, scale=12), nullable=False),
    sa.Column('generated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_final_confidence'),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.analysis_run_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['internal_match_id'], ['matches.internal_match_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['market_probability_id'], ['market_probabilities.market_probability_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quant_prediction_id'], ['quant_predictions.quant_prediction_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('final_prediction_id'),
    sa.UniqueConstraint('analysis_run_id', 'internal_match_id', 'market_key', name='uq_final_prediction')
    )
    op.create_table('market_odds_quotes',
    sa.Column('snapshot_id', sa.String(length=160), nullable=False),
    sa.Column('selection_key', sa.String(length=64), nullable=False),
    sa.Column('odds', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.CheckConstraint('odds > 1', name='ck_market_odds_gt_one'),
    sa.CheckConstraint("selection_key IN ('HOME_WIN', 'DRAW', 'AWAY_WIN')", name='ck_market_odds_selection'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_odds_snapshots.snapshot_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('snapshot_id', 'selection_key')
    )
    op.create_table('market_probability_inputs',
    sa.Column('market_probability_id', sa.String(length=160), nullable=False),
    sa.Column('market_odds_snapshot_id', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['market_odds_snapshot_id'], ['market_odds_snapshots.snapshot_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['market_probability_id'], ['market_probabilities.market_probability_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('market_probability_id', 'market_odds_snapshot_id')
    )
    op.create_table('market_probability_outcomes',
    sa.Column('market_probability_id', sa.String(length=160), nullable=False),
    sa.Column('selection_key', sa.String(length=64), nullable=False),
    sa.Column('probability', sa.Numeric(precision=18, scale=12), nullable=False),
    sa.CheckConstraint('probability >= 0 AND probability <= 1', name='ck_market_probability'),
    sa.ForeignKeyConstraint(['market_probability_id'], ['market_probabilities.market_probability_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('market_probability_id', 'selection_key')
    )
    op.create_table('quant_prediction_outcomes',
    sa.Column('quant_prediction_id', sa.String(length=160), nullable=False),
    sa.Column('selection_key', sa.String(length=64), nullable=False),
    sa.Column('probability', sa.Numeric(precision=18, scale=12), nullable=False),
    sa.CheckConstraint('probability >= 0 AND probability <= 1', name='ck_quant_probability'),
    sa.ForeignKeyConstraint(['quant_prediction_id'], ['quant_predictions.quant_prediction_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('quant_prediction_id', 'selection_key')
    )
    op.create_table('sporttery_bonus_quotes',
    sa.Column('snapshot_id', sa.String(length=160), nullable=False),
    sa.Column('selection_key', sa.String(length=64), nullable=False),
    sa.Column('fixed_bonus', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.CheckConstraint('fixed_bonus > 1', name='ck_sporttery_bonus_gt_one'),
    sa.CheckConstraint("selection_key IN ('HOME_WIN', 'DRAW', 'AWAY_WIN')", name='ck_sporttery_bonus_selection'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['sporttery_bonus_snapshots.snapshot_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('snapshot_id', 'selection_key')
    )
    op.create_table('bet_candidates',
    sa.Column('candidate_id', sa.String(length=160), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=160), nullable=False),
    sa.Column('internal_match_id', sa.String(length=160), nullable=False),
    sa.Column('final_prediction_id', sa.String(length=160), nullable=False),
    sa.Column('sporttery_bonus_snapshot_id', sa.String(length=160), nullable=False),
    sa.Column('market_key', sa.String(length=120), nullable=False),
    sa.Column('selection_key', sa.String(length=64), nullable=False),
    sa.Column('probability_used', sa.Numeric(precision=18, scale=12), nullable=False),
    sa.Column('fixed_bonus', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('break_even_probability', sa.Numeric(precision=18, scale=12), nullable=False),
    sa.Column('ev', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('eligibility_status', sa.String(length=64), nullable=False),
    sa.Column('rejection_code', sa.String(length=80), nullable=True),
    sa.CheckConstraint('fixed_bonus > 1', name='ck_bet_fixed_bonus'),
    sa.CheckConstraint('probability_used >= 0 AND probability_used <= 1', name='ck_bet_probability'),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.analysis_run_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['final_prediction_id'], ['final_predictions.final_prediction_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['internal_match_id'], ['matches.internal_match_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sporttery_bonus_snapshot_id'], ['sporttery_bonus_snapshots.snapshot_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('candidate_id'),
    sa.UniqueConstraint('analysis_run_id', 'internal_match_id', 'market_key', 'selection_key', name='uq_bet_candidate')
    )
    op.create_table('final_prediction_outcomes',
    sa.Column('final_prediction_id', sa.String(length=160), nullable=False),
    sa.Column('selection_key', sa.String(length=64), nullable=False),
    sa.Column('probability', sa.Numeric(precision=18, scale=12), nullable=False),
    sa.CheckConstraint('probability >= 0 AND probability <= 1', name='ck_final_probability'),
    sa.ForeignKeyConstraint(['final_prediction_id'], ['final_predictions.final_prediction_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('final_prediction_id', 'selection_key')
    )
    op.create_table('ticket_candidate_legs',
    sa.Column('ticket_candidate_id', sa.String(length=160), nullable=False),
    sa.Column('leg_no', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.String(length=160), nullable=False),
    sa.Column('internal_match_id', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['bet_candidates.candidate_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['internal_match_id'], ['matches.internal_match_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_candidate_id'], ['ticket_candidates.ticket_candidate_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ticket_candidate_id', 'leg_no'),
    sa.UniqueConstraint('ticket_candidate_id', 'internal_match_id', name='uq_ticket_candidate_match')
    )
    op.create_table('ticket_legs',
    sa.Column('ticket_id', sa.String(length=160), nullable=False),
    sa.Column('leg_no', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.String(length=160), nullable=False),
    sa.Column('internal_match_id', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['bet_candidates.candidate_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['internal_match_id'], ['matches.internal_match_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ticket_id', 'leg_no'),
    sa.UniqueConstraint('ticket_id', 'internal_match_id', name='uq_ticket_match')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_legs')
    op.drop_table('ticket_candidate_legs')
    op.drop_table('final_prediction_outcomes')
    op.drop_table('bet_candidates')
    op.drop_table('sporttery_bonus_quotes')
    op.drop_table('quant_prediction_outcomes')
    op.drop_table('manual_quant_input_outcomes')
    op.drop_table('market_probability_outcomes')
    op.drop_table('market_probability_inputs')
    op.drop_table('market_odds_quotes')
    op.drop_table('final_predictions')
    op.drop_table('analysis_run_matches')
    op.drop_table('tickets')
    op.drop_index('ix_sporttery_bonus_match_time', table_name='sporttery_bonus_snapshots')
    op.drop_table('sporttery_bonus_snapshots')
    op.drop_table('quant_predictions')
    op.drop_table('manual_quant_inputs')
    op.drop_table('provider_match_mappings')
    op.drop_table('market_probabilities')
    op.drop_index('ix_market_odds_match_bookmaker_time', table_name='market_odds_snapshots')
    op.drop_table('market_odds_snapshots')
    op.drop_table('ticket_candidates')
    op.drop_table('portfolios')
    op.drop_index('ix_matches_competition_kickoff', table_name='matches')
    op.drop_table('matches')
    op.drop_table('teams')
    op.drop_table('providers')
    op.drop_table('competitions')
    op.drop_table('bookmakers')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
