"""add live source ingestion

Revision ID: 3cb19bcbdd88
Revises: c4e8a1d7f205
Create Date: 2026-09-04 10:36:49.854571
"""

from typing import Sequence, Union, cast

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Connection

from football_system.infrastructure.database.immutability import (
    LIVE_SOURCE_V1_INSERT_KEYS,
    install_live_source_v1_triggers,
)


revision: str = "3cb19bcbdd88"
down_revision: Union[str, None] = "c4e8a1d7f205"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

LIVE_SOURCE_V1_TABLES = tuple(LIVE_SOURCE_V1_INSERT_KEYS)


def upgrade() -> None:
    _require_sqlite_dialect()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "live_analysis_preparations",
        sa.Column("preparation_id", sa.String(length=160), nullable=False),
        sa.Column("schema_version", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("decision_as_of_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kickoff_from_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kickoff_to_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("competition_id", sa.String(length=160), nullable=False),
        sa.Column("season_id", sa.String(length=160), nullable=False),
        sa.Column("allow_partial_inputs", sa.Boolean(), nullable=False),
        sa.Column("policy_version", sa.String(length=80), nullable=False),
        sa.Column("maximum_odds_age_seconds", sa.Integer(), nullable=False),
        sa.Column("minimum_bookmaker_count", sa.Integer(), nullable=False),
        sa.Column("expected_match_ids_json", sa.Text(), nullable=False),
        sa.Column("match_count", sa.Integer(), nullable=False),
        sa.Column("ready_match_count", sa.Integer(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("preparation_json", sa.Text(), nullable=False),
        sa.Column("report_hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "json_valid(expected_match_ids_json) = 1 AND json_type(expected_match_ids_json) = 'array' AND json_valid(preparation_json) = 1 AND json_type(preparation_json) = 'object'",
            name="ck_live_analysis_preparation_json",
        ),
        sa.CheckConstraint(
            "length(report_hash) = 64 AND report_hash NOT GLOB '*[^0-9a-f]*'",
            name="ck_live_analysis_preparation_hash",
        ),
        sa.CheckConstraint(
            "policy_version = 'LIVE_ANALYSIS_INPUT_POLICY_V1' AND maximum_odds_age_seconds > 0 AND minimum_bookmaker_count > 0",
            name="ck_live_analysis_preparation_policy",
        ),
        sa.CheckConstraint(
            "schema_version = 'LIVE_ANALYSIS_PREPARATION_V1'",
            name="ck_live_analysis_preparation_schema",
        ),
        sa.CheckConstraint(
            "status IN ('ANALYSIS_INPUT_READY', 'NO_ANALYSIS_INSUFFICIENT_DATA')",
            name="ck_live_analysis_preparation_status",
        ),
        sa.CheckConstraint(
            "decision_as_of_at_utc <= created_at_utc AND kickoff_from_utc <= kickoff_to_utc",
            name="ck_live_analysis_preparation_timeline",
        ),
        sa.CheckConstraint(
            "match_count >= ready_match_count AND ready_match_count >= 0",
            name="ck_live_analysis_preparation_counts",
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"], ["competitions.competition_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("preparation_id"),
        sa.UniqueConstraint("report_hash", name="uq_live_analysis_preparation_hash"),
    )
    op.create_index(
        "ix_live_analysis_preparation_scope_cutoff",
        "live_analysis_preparations",
        ["competition_id", "season_id", "decision_as_of_at_utc"],
        unique=False,
    )
    op.create_table(
        "live_source_ingestions",
        sa.Column("ingestion_id", sa.String(length=160), nullable=False),
        sa.Column("schema_version", sa.String(length=80), nullable=False),
        sa.Column("source_kind", sa.String(length=64), nullable=False),
        sa.Column("provider_id", sa.String(length=160), nullable=False),
        sa.Column("data_mode", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("identity_cutoff_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_ingested_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("persisted_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("requested_match_ids_json", sa.Text(), nullable=False),
        sa.Column("artifact_count", sa.Integer(), nullable=False),
        sa.Column("snapshot_count", sa.Integer(), nullable=False),
        sa.Column("mapping_count", sa.Integer(), nullable=False),
        sa.Column("issue_count", sa.Integer(), nullable=False),
        sa.Column("consensus_count", sa.Integer(), nullable=False),
        sa.Column("capture_json", sa.Text(), nullable=False),
        sa.Column("capture_hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "data_mode = 'LIVE_STRICT'", name="ck_live_source_ingestion_data_mode"
        ),
        sa.CheckConstraint(
            "json_valid(requested_match_ids_json) = 1 AND json_type(requested_match_ids_json) = 'array' AND json_valid(capture_json) = 1 AND json_type(capture_json) = 'object'",
            name="ck_live_source_ingestion_json",
        ),
        sa.CheckConstraint(
            "length(capture_hash) = 64 AND capture_hash NOT GLOB '*[^0-9a-f]*'",
            name="ck_live_source_ingestion_hash",
        ),
        sa.CheckConstraint(
            "schema_version = 'LIVE_SOURCE_INGESTION_V1'",
            name="ck_live_source_ingestion_schema",
        ),
        sa.CheckConstraint(
            "source_kind IN ('MARKET_ODDS', 'SPORTTERRY')",
            name="ck_live_source_ingestion_kind",
        ),
        sa.CheckConstraint(
            "status IN ('COMPLETED', 'COMPLETED_WITH_ISSUES')",
            name="ck_live_source_ingestion_status",
        ),
        sa.CheckConstraint(
            "artifact_count > 0 AND snapshot_count >= 0 AND mapping_count >= 0 AND issue_count >= 0 AND consensus_count >= 0",
            name="ck_live_source_ingestion_counts",
        ),
        sa.CheckConstraint(
            "identity_cutoff_at_utc <= source_ingested_at_utc AND source_ingested_at_utc <= persisted_at_utc",
            name="ck_live_source_ingestion_timeline",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["providers.provider_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("ingestion_id"),
        sa.UniqueConstraint("capture_hash", name="uq_live_source_ingestion_hash"),
    )
    op.create_index(
        "ix_live_source_ingestion_kind_persisted",
        "live_source_ingestions",
        ["source_kind", "persisted_at_utc"],
        unique=False,
    )
    op.create_index(
        "ix_live_source_ingestion_provider_persisted",
        "live_source_ingestions",
        ["provider_id", "persisted_at_utc"],
        unique=False,
    )
    op.create_table(
        "live_identity_reviews",
        sa.Column("review_id", sa.String(length=160), nullable=False),
        sa.Column("schema_version", sa.String(length=80), nullable=False),
        sa.Column("source_ingestion_id", sa.String(length=160), nullable=False),
        sa.Column("reviewed_by", sa.String(length=160), nullable=False),
        sa.Column("reviewed_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("imported_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mapping_count", sa.Integer(), nullable=False),
        sa.Column("review_json", sa.Text(), nullable=False),
        sa.Column("review_hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "json_valid(review_json) = 1 AND json_type(review_json) = 'object'",
            name="ck_live_identity_review_json",
        ),
        sa.CheckConstraint(
            "length(review_hash) = 64 AND review_hash NOT GLOB '*[^0-9a-f]*'",
            name="ck_live_identity_review_hash",
        ),
        sa.CheckConstraint(
            "schema_version = 'LIVE_IDENTITY_REVIEW_V1'",
            name="ck_live_identity_review_schema",
        ),
        sa.CheckConstraint(
            "mapping_count > 0", name="ck_live_identity_review_mapping_count"
        ),
        sa.CheckConstraint(
            "reviewed_at_utc <= imported_at_utc",
            name="ck_live_identity_review_timeline",
        ),
        sa.ForeignKeyConstraint(
            ["source_ingestion_id"],
            ["live_source_ingestions.ingestion_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("review_id"),
        sa.UniqueConstraint("review_hash", name="uq_live_identity_review_hash"),
        sa.UniqueConstraint(
            "review_id", "source_ingestion_id", name="uq_live_identity_review_source"
        ),
    )
    op.create_table(
        "live_source_ingestion_artifacts",
        sa.Column("ingestion_id", sa.String(length=160), nullable=False),
        sa.Column("artifact_id", sa.String(length=160), nullable=False),
        sa.Column("artifact_no", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_path", sa.String(length=4096), nullable=False),
        sa.Column("captured_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(payload_sha256) = 64 AND payload_sha256 NOT GLOB '*[^0-9a-f]*'",
            name="ck_live_source_artifact_hash",
        ),
        sa.CheckConstraint(
            "role IN ('RAW_RESPONSE', 'MANUAL_DOCUMENT', 'SOURCE_ARTIFACT')",
            name="ck_live_source_artifact_role",
        ),
        sa.CheckConstraint("artifact_no >= 0", name="ck_live_source_artifact_no"),
        sa.CheckConstraint(
            "captured_at_utc <= available_at_utc",
            name="ck_live_source_artifact_timeline",
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_id"],
            ["live_source_ingestions.ingestion_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("ingestion_id", "artifact_id"),
        sa.UniqueConstraint(
            "ingestion_id", "artifact_no", name="uq_live_source_artifact_no"
        ),
    )
    op.create_table(
        "live_source_ingestion_issues",
        sa.Column("ingestion_id", sa.String(length=160), nullable=False),
        sa.Column("issue_id", sa.String(length=160), nullable=False),
        sa.Column("issue_no", sa.Integer(), nullable=False),
        sa.Column("source_kind", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("provider_id", sa.String(length=160), nullable=False),
        sa.Column("external_namespace", sa.String(length=80), nullable=True),
        sa.Column("external_match_id", sa.String(length=160), nullable=True),
        sa.Column("requested_match_id", sa.String(length=160), nullable=True),
        sa.Column("candidates_json", sa.Text(), nullable=False),
        sa.Column("code", sa.String(length=160), nullable=False),
        sa.Column("detail", sa.String(length=240), nullable=False),
        sa.Column("provider_identity_json", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "json_valid(candidates_json) = 1 AND json_type(candidates_json) = 'array'",
            name="ck_live_source_issue_candidates_json",
        ),
        sa.CheckConstraint(
            "source_kind IN ('MARKET_ODDS', 'SPORTTERRY')",
            name="ck_live_source_issue_kind",
        ),
        sa.CheckConstraint(
            "(external_namespace IS NULL AND external_match_id IS NULL) OR (external_namespace IS NOT NULL AND external_match_id IS NOT NULL)",
            name="ck_live_source_issue_external_identity",
        ),
        sa.CheckConstraint("issue_no >= 0", name="ck_live_source_issue_no"),
        sa.ForeignKeyConstraint(
            ["ingestion_id"],
            ["live_source_ingestions.ingestion_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["providers.provider_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("ingestion_id", "issue_id"),
        sa.UniqueConstraint("ingestion_id", "issue_no", name="uq_live_source_issue_no"),
    )
    op.create_table(
        "live_identity_review_mappings",
        sa.Column("review_id", sa.String(length=160), nullable=False),
        sa.Column("mapping_no", sa.Integer(), nullable=False),
        sa.Column("source_ingestion_id", sa.String(length=160), nullable=False),
        sa.Column("source_issue_id", sa.String(length=160), nullable=False),
        sa.Column("provider_id", sa.String(length=160), nullable=False),
        sa.Column("external_namespace", sa.String(length=80), nullable=False),
        sa.Column("external_match_id", sa.String(length=160), nullable=False),
        sa.Column("internal_match_id", sa.String(length=160), nullable=False),
        sa.Column("provider_mapping_id", sa.String(length=160), nullable=False),
        sa.CheckConstraint(
            "mapping_no >= 0", name="ck_live_identity_review_mapping_no"
        ),
        sa.ForeignKeyConstraint(
            ["internal_match_id"], ["matches.internal_match_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["providers.provider_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["provider_mapping_id"],
            ["provider_match_mappings.mapping_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["review_id", "source_ingestion_id"],
            [
                "live_identity_reviews.review_id",
                "live_identity_reviews.source_ingestion_id",
            ],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_ingestion_id", "source_issue_id"],
            [
                "live_source_ingestion_issues.ingestion_id",
                "live_source_ingestion_issues.issue_id",
            ],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("review_id", "mapping_no"),
        sa.UniqueConstraint(
            "review_id",
            "provider_id",
            "external_namespace",
            "external_match_id",
            name="uq_live_identity_review_external",
        ),
    )
    op.create_table(
        "live_source_ingestion_mappings",
        sa.Column("ingestion_id", sa.String(length=160), nullable=False),
        sa.Column("mapping_role", sa.String(length=64), nullable=False),
        sa.Column("mapping_id", sa.String(length=160), nullable=False),
        sa.Column("mapping_no", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "mapping_role IN ('SOURCE', 'CONSENSUS')",
            name="ck_live_source_mapping_role",
        ),
        sa.CheckConstraint("mapping_no >= 0", name="ck_live_source_mapping_no"),
        sa.ForeignKeyConstraint(
            ["ingestion_id"],
            ["live_source_ingestions.ingestion_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["mapping_id"], ["provider_match_mappings.mapping_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("ingestion_id", "mapping_role", "mapping_id"),
        sa.UniqueConstraint(
            "ingestion_id",
            "mapping_role",
            "mapping_no",
            name="uq_live_source_mapping_no",
        ),
    )
    op.create_table(
        "live_source_ingestion_market_snapshots",
        sa.Column("ingestion_id", sa.String(length=160), nullable=False),
        sa.Column("snapshot_role", sa.String(length=64), nullable=False),
        sa.Column("snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("snapshot_no", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "snapshot_role IN ('SOURCE', 'CONSENSUS')",
            name="ck_live_source_market_role",
        ),
        sa.CheckConstraint("snapshot_no >= 0", name="ck_live_source_market_no"),
        sa.ForeignKeyConstraint(
            ["ingestion_id"],
            ["live_source_ingestions.ingestion_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["market_odds_snapshots.snapshot_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("ingestion_id", "snapshot_role", "snapshot_id"),
        sa.UniqueConstraint(
            "ingestion_id", "snapshot_id", name="uq_live_source_market_membership"
        ),
        sa.UniqueConstraint(
            "ingestion_id",
            "snapshot_role",
            "snapshot_no",
            name="uq_live_source_market_no",
        ),
    )
    op.create_table(
        "live_source_ingestion_sporttery_snapshots",
        sa.Column("ingestion_id", sa.String(length=160), nullable=False),
        sa.Column("snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("snapshot_no", sa.Integer(), nullable=False),
        sa.Column("manual_document_artifact_id", sa.String(length=160), nullable=False),
        sa.Column("source_artifact_id", sa.String(length=160), nullable=False),
        sa.Column("provenance_json", sa.Text(), nullable=False),
        sa.Column("provenance_hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "json_valid(provenance_json) = 1 AND json_type(provenance_json) = 'object'",
            name="ck_live_source_sporttery_provenance_json",
        ),
        sa.CheckConstraint(
            "length(provenance_hash) = 64 AND provenance_hash NOT GLOB '*[^0-9a-f]*'",
            name="ck_live_source_sporttery_provenance_hash",
        ),
        sa.CheckConstraint("snapshot_no >= 0", name="ck_live_source_sporttery_no"),
        sa.ForeignKeyConstraint(
            ["ingestion_id", "manual_document_artifact_id"],
            [
                "live_source_ingestion_artifacts.ingestion_id",
                "live_source_ingestion_artifacts.artifact_id",
            ],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_id", "source_artifact_id"],
            [
                "live_source_ingestion_artifacts.ingestion_id",
                "live_source_ingestion_artifacts.artifact_id",
            ],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_id"],
            ["live_source_ingestions.ingestion_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["sporttery_bonus_snapshots.snapshot_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("ingestion_id", "snapshot_id"),
        sa.UniqueConstraint(
            "ingestion_id", "snapshot_no", name="uq_live_source_sporttery_no"
        ),
    )
    op.create_table(
        "live_analysis_preparation_matches",
        sa.Column("preparation_id", sa.String(length=160), nullable=False),
        sa.Column("internal_match_id", sa.String(length=160), nullable=False),
        sa.Column("match_no", sa.Integer(), nullable=False),
        sa.Column("ready", sa.Boolean(), nullable=False),
        sa.Column("fixture_observation_id", sa.String(length=160), nullable=True),
        sa.Column("market_ingestion_id", sa.String(length=160), nullable=True),
        sa.Column("market_consensus_snapshot_id", sa.String(length=160), nullable=True),
        sa.Column("sporttery_ingestion_id", sa.String(length=160), nullable=True),
        sa.Column("sporttery_bonus_snapshot_id", sa.String(length=160), nullable=True),
        sa.Column("bookmaker_count", sa.Integer(), nullable=False),
        sa.Column("odds_age_seconds", sa.Integer(), nullable=True),
        sa.Column("reason_codes_json", sa.Text(), nullable=False),
        sa.Column("data_quality_json", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "json_valid(reason_codes_json) = 1 AND json_type(reason_codes_json) = 'array' AND json_valid(data_quality_json) = 1 AND json_type(data_quality_json) = 'object'",
            name="ck_live_analysis_match_json",
        ),
        sa.CheckConstraint(
            "(market_ingestion_id IS NULL AND market_consensus_snapshot_id IS NULL) OR (market_ingestion_id IS NOT NULL AND market_consensus_snapshot_id IS NOT NULL)",
            name="ck_live_analysis_match_market_pair",
        ),
        sa.CheckConstraint(
            "(sporttery_ingestion_id IS NULL AND sporttery_bonus_snapshot_id IS NULL) OR (sporttery_ingestion_id IS NOT NULL AND sporttery_bonus_snapshot_id IS NOT NULL)",
            name="ck_live_analysis_match_sporttery_pair",
        ),
        sa.CheckConstraint(
            "bookmaker_count >= 0 AND (odds_age_seconds IS NULL OR odds_age_seconds >= 0)",
            name="ck_live_analysis_match_metrics",
        ),
        sa.CheckConstraint("match_no >= 0", name="ck_live_analysis_match_no"),
        sa.ForeignKeyConstraint(
            ["fixture_observation_id"],
            ["fixture_observations.observation_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["market_ingestion_id", "market_consensus_snapshot_id"],
            [
                "live_source_ingestion_market_snapshots.ingestion_id",
                "live_source_ingestion_market_snapshots.snapshot_id",
            ],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["preparation_id"],
            ["live_analysis_preparations.preparation_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sporttery_ingestion_id", "sporttery_bonus_snapshot_id"],
            [
                "live_source_ingestion_sporttery_snapshots.ingestion_id",
                "live_source_ingestion_sporttery_snapshots.snapshot_id",
            ],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("preparation_id", "internal_match_id"),
        sa.UniqueConstraint(
            "preparation_id", "match_no", name="uq_live_analysis_match_no"
        ),
    )
    op.create_table(
        "live_market_consensus_lineages",
        sa.Column("ingestion_id", sa.String(length=160), nullable=False),
        sa.Column("consensus_snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("policy", sa.String(length=80), nullable=False),
        sa.Column("internal_match_id", sa.String(length=160), nullable=False),
        sa.Column("source_snapshot_key", sa.String(length=160), nullable=False),
        sa.Column("constituent_count", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "policy = 'MARKET_CONSENSUS_MEDIAN_V1'",
            name="ck_live_market_consensus_policy",
        ),
        sa.CheckConstraint(
            "constituent_count > 0", name="ck_live_market_consensus_count"
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_id", "consensus_snapshot_id"],
            [
                "live_source_ingestion_market_snapshots.ingestion_id",
                "live_source_ingestion_market_snapshots.snapshot_id",
            ],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["internal_match_id"], ["matches.internal_match_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("ingestion_id", "consensus_snapshot_id"),
    )
    op.create_table(
        "live_market_consensus_constituents",
        sa.Column("ingestion_id", sa.String(length=160), nullable=False),
        sa.Column("consensus_snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("source_snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("constituent_no", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.String(length=160), nullable=False),
        sa.Column("bookmaker_id", sa.String(length=160), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "length(payload_hash) = 64 AND payload_hash NOT GLOB '*[^0-9a-f]*'",
            name="ck_live_market_constituent_hash",
        ),
        sa.CheckConstraint("constituent_no >= 0", name="ck_live_market_constituent_no"),
        sa.ForeignKeyConstraint(
            ["bookmaker_id"], ["bookmakers.bookmaker_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_id", "consensus_snapshot_id"],
            [
                "live_market_consensus_lineages.ingestion_id",
                "live_market_consensus_lineages.consensus_snapshot_id",
            ],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_id", "source_snapshot_id"],
            [
                "live_source_ingestion_market_snapshots.ingestion_id",
                "live_source_ingestion_market_snapshots.snapshot_id",
            ],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["providers.provider_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint(
            "ingestion_id", "consensus_snapshot_id", "source_snapshot_id"
        ),
        sa.UniqueConstraint(
            "ingestion_id",
            "consensus_snapshot_id",
            "constituent_no",
            name="uq_live_market_constituent_no",
        ),
    )
    install_live_source_v1_triggers(cast(Connection, _AlembicConnection()))
    # ### end Alembic commands ###


def downgrade() -> None:
    _require_sqlite_dialect()
    _require_empty_live_source_lineage()
    _drop_triggers()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("live_market_consensus_constituents")
    op.drop_table("live_market_consensus_lineages")
    op.drop_table("live_analysis_preparation_matches")
    op.drop_table("live_source_ingestion_sporttery_snapshots")
    op.drop_table("live_source_ingestion_market_snapshots")
    op.drop_table("live_source_ingestion_mappings")
    op.drop_table("live_identity_review_mappings")
    op.drop_table("live_source_ingestion_issues")
    op.drop_table("live_source_ingestion_artifacts")
    op.drop_table("live_identity_reviews")
    op.drop_index(
        "ix_live_source_ingestion_provider_persisted",
        table_name="live_source_ingestions",
    )
    op.drop_index(
        "ix_live_source_ingestion_kind_persisted", table_name="live_source_ingestions"
    )
    op.drop_table("live_source_ingestions")
    op.drop_index(
        "ix_live_analysis_preparation_scope_cutoff",
        table_name="live_analysis_preparations",
    )
    op.drop_table("live_analysis_preparations")
    # ### end Alembic commands ###


class _AlembicConnection:
    dialect = type("_Dialect", (), {"name": "sqlite"})()

    def exec_driver_sql(self, statement: str) -> None:
        op.execute(statement)


def _drop_triggers() -> None:
    lineage_tables = (
        "live_source_ingestion_artifacts",
        "live_source_ingestion_mappings",
        "live_source_ingestion_market_snapshots",
        "live_market_consensus_lineages",
        "live_market_consensus_constituents",
        "live_source_ingestion_sporttery_snapshots",
        "live_source_ingestion_issues",
        "live_identity_review_mappings",
        "live_analysis_preparation_matches",
    )
    for table_name in LIVE_SOURCE_V1_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table_name}_immutable_insert_existing")
        for action in ("update", "delete"):
            op.execute(f"DROP TRIGGER IF EXISTS trg_{table_name}_append_only_{action}")
    for table_name in lineage_tables:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table_name}_live_lineage_insert")


def _require_empty_live_source_lineage() -> None:
    if op.get_context().as_sql:
        raise RuntimeError(
            "offline live-source downgrade is unsupported because lineage must be checked"
        )
    connection = op.get_bind()
    populated = any(
        connection.scalar(sa.text(f"SELECT EXISTS (SELECT 1 FROM {table_name})"))
        for table_name in (
            "live_source_ingestions",
            "live_identity_reviews",
            "live_analysis_preparations",
        )
    )
    if populated:
        raise RuntimeError(
            "cannot downgrade live-source schema while immutable lineage exists"
        )


def _require_sqlite_dialect() -> None:
    dialect = op.get_context().dialect.name
    if dialect != "sqlite":
        raise RuntimeError(
            f"Unsupported database backend '{dialect}'; "
            "football-system v0.4.0 supports SQLite only."
        )
